config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :locations
  root "pages#home"
  resources :sessions, only:[:new, :create, :destroy] 
  resources :users do
    member do 
      put "like" 
      put "dislike"
    end
  end
  get "login", to: "sessions#new" 
  get "/join_the_team", to: "users#new"
  delete "/logout", to: "sessions#destroy"
  resources :users do
   collection do
     match 'search' => 'users#search', via: [:get, :post], as: :search
   end
 end 

 get '/photoshoots', to: 'photoshoot_page#photoshoot'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  mount_uploader :profile_photo, ProfilePhotoUploader
  acts_as_votable
  

  has_many :photos, class_name: "Photo", foreign_key: "photographer_id"
  belongs_to :location, class_name: "Location", foreign_key: "location_id"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new user_params
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user } #notice: 'User was successfully created.' 
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
     @q = User.search(params[:q])
     @users = @q.result(distinct: true)
     render :index
   end

def like
  @user = User.find(params[:id])
  @user.liked_by current_user
  respond_to do |format|
    format.html {redirect_to :back}
  end
end

def dislike
  @user = User.find(params[:id])
  @user.disliked_by current_user
  respond_to do |format|
    format.html {redirect_to :back}
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role, :phone_number, :country, :location_id, :currency, :price, :upload_professional_photo, :profile_photo)
    end
    end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= f.label :location_id %><br>
  <%= f.collection_select :location_id, Location.all, :id, :city %>
</div>
<div class="field">
  <%= f.label :profile_photo %><br />
  <%= f.file_field :profile_photo %>
</div>
<%= f.hidden_field :role, value: params["role"]  %>
<% if params["role"] == "p" %>
<div class="field">
  <%= f.label :phone_number %><br>
  <%= f.text_field :phone_number %>
</div>
<div class="field">
  <%= f.label :currency %>
  <%= f.select :currency, [['GBP'],['EUR'],['USD'], ['CNY']] %>
</div>
<div class="field">
  <%= f.label :price %><br>
  <%= f.number_field :price %>
</div>
<div class="field">
  <%= f.label :upload_professional_photo %><br>
  <%= f.text_field :upload_professional_photo %>
</div>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% @users.each do |user| %>
    <% if user.role == "p" %>
  <ul>
    <li><%= link_to "#{user.first_name} #{user.last_name}", user %></li>
    <li><%= user.email %></li>
  </ul>
 <% end %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @user.profile_photo.url, width: 200 %>
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>
<p>
  <strong>Country:</strong>
  <%= @user.location.country %>
</p>
<p>
  <strong>City:</strong>
  <%= link_to @user.location.city, @user.location %>
</p>

<% if !!current_user %>
<% if @user.role == "p" %>
<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>
<p>
  <strong>Currency:</strong>
  <%= @user.currency %>
</p>
<p>
  <strong>Price for 2 hours photoshoot:</strong>
  <%= @user.price %>
</p>

<h3><%= "#{@user.first_name}'s Portfolio"%></h3>
<li class="photo large-4 medium-6 columns">
  <ul>
    <% @user.photos.each do |photo| %>
    <li><%= link_to(image_tag(photo.image, width: '200'), photo) %></li>
    <% end %>
  </ul>
</li>

<%= link_to "Like", like_user_path(@user), method: :put %>
<%= link_to "Dislike", dislike_user_path(@user), method: :put %>
<%=  @user.get_likes.size %>
<%=  @user.get_dislikes.size %>

<% end %>
<% else %>
<p>
  <strong>Price for 2 hours photoshoot:</strong>
  <%= @user.price %>
</p>

<h3><%= "#{@user.first_name}'s Portfolio"%></h3>
<ul>
  <% @user.photos.each do |photo| %>
  <li><%= link_to(image_tag(photo.image, width: '200'), photo) %></li>
</ul>
<% end %>
</li>
<% end %>