config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :locations
  root "pages#home"
  resources :sessions, only:[:new, :create, :destroy] 
  resources :users do
    member do 
      put "like" 
      put "dislike"
    end
  end
  get "login", to: "sessions#new" 
  get "/join_the_team", to: "users#new"
  delete "/logout", to: "sessions#destroy"
  resources :users do
   collection do
     match 'search' => 'users#search', via: [:get, :post], as: :search
   end
 end 

 get '/photoshoots', to: 'photoshoot_page#photoshoot'
end

app/views/layouts/_header.html.erb
<header>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Reisefoto</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
    <% if current_user %>
    <li><a><%= current_user.first_name %></a></li>
    <% end %>
    <li class="active"><%= search_form_for @q, url: search_users_path, html: { method: :post }  do |f| %>
       <%= f.text_field :first_name_cont %></li>
       <li><%= f.submit class: 'button' %></li>
        <% end %>
    </ul>
    <ul class="left">
      <li><a href="/users">Photographers</a></li>
        <% if current_user %>
        <li><%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?"} %></li>
        <li><%= link_to 'Edit Profile', edit_user_path(current_user) %> </li>
        <% end %>
        <li><a href="/photoshoots">Photoshoot ideas</a></li>
        <% unless current_user %>
        <li><a href="/users/new?role=p">Join The Team</a></li>
        <% end %>
        <% unless current_user %>
        <li><a href="/login">Log in </a></li>
        <li><%= link_to 'Sign up', "/users/new?role=c" %></li> 
        <% end %>
    </ul>
  </section>
</nav>
</header>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
  <% if current_user %>
  <% else%>
  <% link_to "Please Login", login_path %>
  <% end %>

  <%= yield %>
</body>
</html>